services:
  - type: web
    name: attendance-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm run start:render
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 10000
